export const CATEGORY_LABELS: Record<string, string> = {
  score_engage: "Engagement",
  score_env: "Environment",
  score_health: "Health",
  score_house: "Housing",
  score_opp: "Opportunity",
  score_prox: "Neighborhood",
  score_trans: "Transportation",
};

export const METRIC_LABELS: Record<string, string> = {
  met_engage_broad: "Broadband Access",
  met_engage_civic: "Civic Engagement",
  met_engage_culture: "Cultural Institutions",
  met_engage_social: "Social Involvement",
  met_engage_vote: "Voter Participation",
  met_env_air: "Air Quality",
  met_env_pollute: "Pollution Exposure",
  met_env_road: "Road Safety",
  met_env_water: "Water Quality",
  met_health_exercise: "Exercise Opportunities",
  met_health_hospital: "Hospital Distance",
  met_health_obese: "Obesity Rate",
  met_health_sate: "Health Satisfaction",
  met_health_short: "Preventable Hospitalizations",
  met_health_smoke: "Smoking Rate",
  met_house_access_step: "Zero-Step Entrance",
  met_house_burden: "Housing Burden",
  met_house_cost: "Monthly Housing Cost",
  met_house_multifam: "Multi-Family Housing",
  met_house_subsidy: "Subsidized Housing",
  met_opp_age: "Age Diversity",
  met_opp_grad: "High School Graduation",
  met_opp_income: "Income Inequality",
  met_opp_jobs: "Jobs per Worker",
  met_prox_activity: "Activity Density",
  met_prox_auto: "Auto-Oriented Destinations",
  met_prox_land_use: "Land Use Mix",
  met_prox_lib: "Library Access",
  met_prox_market: "Grocery Store Access",
  met_prox_park: "Park Access",
  met_prox_sec: "Secondary Education Access",
  met_prox_trans: "Transit Access",
  met_prox_vacant: "Vacant Housing",
  met_trans_access: "ADA-Accessible Stations",
  met_trans_cost: "Transportation Cost",
  met_trans_delay: "Congestion",
  met_trans_fatal: "Traffic Fatalities",
  met_trans_freq: "Transit Frequency",
  met_trans_limit: "Speed Limits",
  met_trans_walk: "Walk Score",
};

export const POLICY_LABELS: Record<string, string> = {
  pol_engage_broad: "Broadband Plan",
  pol_engage_lgbt: "LGBT Protections",
  pol_engage_right: "Right to Counsel",
  pol_engage_vote: "Voting Access",
  pol_env_connect: "Complete Streets",
  pol_env_eff: "Energy Efficiency",
  pol_env_hazard: "Hazard Mitigation",
  pol_health_smoke: "Smoke-Free Laws",
  pol_house_adu: "ADU Permitted",
  pol_house_foreclose: "Foreclosure Prevention",
  pol_house_mfg: "Manufactured Housing",
  pol_house_trust: "Housing Trust Fund",
  pol_house_visit: "Visitability Standards",
  pol_mult_age_friend: "Age-Friendly Community",
  pol_opp_credit: "Credit Protections",
  pol_opp_leave: "Paid Leave",
  pol_opp_wage: "Minimum Wage",
  pol_prox_tod: "Transit-Oriented Development",
  pol_trans_coord: "Transit Coordination",
  pol_trans_full_st: "Complete Streets Policy",
  pol_trans_vol: "Volunteer Transit",
};

export const DEMOGRAPHIC_LABELS: Record<string, string> = {
  demo_50: "Population 50+",
  demo_65: "Population 65+",
  demo_african: "Black/African American",
  demo_asian: "Asian",
  demo_disable: "Disability",
  demo_hawaiian: "Native Hawaiian/Pacific Islander",
  demo_hisp: "Hispanic/Latino",
  demo_income: "Median Income",
  demo_indian: "American Indian/Alaska Native",
  demo_life_ex: "Life Expectancy",
  demo_more_races: "Two or More Races",
  demo_noveh: "No Vehicle",
  demo_other_race: "Other Race",
  demo_pop: "Total Population",
  demo_poverty: "Poverty Rate",
  demo_up_mobile: "Upward Mobility",
  demo_white: "White",
};

export const METRIC_GROUPS: Record<string, string[]> = {
  Engagement: [
    "met_engage_broad",
    "met_engage_civic",
    "met_engage_culture",
    "met_engage_social",
    "met_engage_vote",
  ],
  Environment: [
    "met_env_air",
    "met_env_pollute",
    "met_env_road",
    "met_env_water",
  ],
  Health: [
    "met_health_exercise",
    "met_health_hospital",
    "met_health_obese",
    "met_health_sate",
    "met_health_short",
    "met_health_smoke",
  ],
  Housing: [
    "met_house_access_step",
    "met_house_burden",
    "met_house_cost",
    "met_house_multifam",
    "met_house_subsidy",
  ],
  Opportunity: [
    "met_opp_age",
    "met_opp_grad",
    "met_opp_income",
    "met_opp_jobs",
  ],
  Neighborhood: [
    "met_prox_activity",
    "met_prox_auto",
    "met_prox_land_use",
    "met_prox_lib",
    "met_prox_market",
    "met_prox_park",
    "met_prox_sec",
    "met_prox_trans",
    "met_prox_vacant",
  ],
  Transportation: [
    "met_trans_access",
    "met_trans_cost",
    "met_trans_delay",
    "met_trans_fatal",
    "met_trans_freq",
    "met_trans_limit",
    "met_trans_walk",
  ],
};
